apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: busybox1
    image: busybox
    args:
    - sleep
    - "1000"

  - name: busybox2
    image: busybox
    args:
    - sleep
    - "1000"
